FROM ubuntu:17.04

#####
# Configure Environment Variables
###############################

# # Ensure UTF-8 lang and locale
ENV LANG       en_US.UTF-8
ENV LANGUAGE   en_US:en 
ENV LC_ALL     en_US.UTF-8
ENV TZ         America/Los_Angeles

ENV DEBIAN_FRONTEND noninteractive


#####
# Configure APT Cacher Proxy
###############################

#RUN  echo 'Acquire::http { Proxy "http://apt-cache-proxy:3142"; };' >> /etc/apt/apt.conf.d/01proxy


#####
# Update and Install Packages
###############################

RUN apt-get clean && apt-get -y update && apt-get install -y software-properties-common

#add-apt-repository -y ppa:team-xbmc/unstable && \
#add-apt-repository -y ppa:wsnipex/vaapi && \

RUN add-apt-repository -y multiverse && \
add-apt-repository -y ppa:team-xbmc/ppa && \
add-apt-repository -y ppa:jlbarriere68/ppa && \
apt-get -y update && \
apt-get purge kodi-pvr-mythtv* && \
apt-get -y install \
pulseaudio \
strace \
kodi \
kodi-pvr-mythtv \
kodi-visualization-projectm \
kodi-visualization-shadertoy \
kodi-visualization-spectrum \
dbus-x11 \
vainfo \
x11-apps \
libcurl4-openssl-dev \
x11-xserver-utils \
coreutils \
nodejs \
npm \
kodi-inputstream-adaptive \
ethtool \
iputils-tracepath \
iputils-ping


#####
# Install and configure 'kodi'
###############################

ADD kodi_config_files.tar.gz /


#####
# Nodejs workaround
###############################

RUN ln /usr/bin/nodejs /usr/bin/node


#####
# Expose Ports and set entrypoint
###############################

EXPOSE 8080
EXPOSE 9090
EXPOSE 1900
EXPOSE 9777

CMD ["/usr/local/bin/launchKodi.sh"]


#####
# Configure 'kodi' user and group
###############################

RUN groupadd -g {{USER_GID}} {{USER}} && \
useradd {{USER}} -u {{USER_UID}} -g {{USER}} && \
echo "{{USER}}:{{PASSWORD}}" | chpasswd

RUN mkdir -p /home/{{USER}}/.config/pulse /home/{{USER}}/.pulse /home/{{USER}}/.kodi/temp
RUN chown {{USER}}:{{USER}} -R /home/{{USER}}


#####
# Fix Timezone
###############################

RUN apt-get -y install tzdata
RUN echo "America/Los_Angeles" > /etc/timezone
RUN dpkg-reconfigure -f noninteractive tzdata


#####
# Clean up
###############################

RUN apt-get -y clean && \
rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

USER {{USER}}