FROM ubuntu:16.04

#####
# Configure Environment Variables
#####

# # Ensure UTF-8 lang and locale
RUN locale-gen en_US.UTF-8
ENV LANG       en_US.UTF-8
ENV LC_ALL     en_US.UTF-8
ENV TZ         America/Los_Angeles

ENV DEBIAN_FRONTEND noninteractive

#####
# Configure APT Cacher Proxy
#####

RUN  echo 'Acquire::http { Proxy "http://apt-cache-proxy:3142"; };' >> /etc/apt/apt.conf.d/01proxy


#####
# Update and Install Packages
#####

RUN apt-get -y update && \
apt-get -y dist-upgrade

RUN apt-get install -y software-properties-common

#add-apt-repository -y ppa:team-xbmc/ppa && \

RUN add-apt-repository -y multiverse && \
add-apt-repository -y ppa:team-xbmc/unstable && \
add-apt-repository -y ppa:wsnipex/vaapi && \
add-apt-repository -y ppa:jlbarriere68/ppa && \
apt-get -y update

RUN apt-get purge kodi-pvr-mythtv*

RUN apt-get -y install \
pulseaudio \
strace \
kodi \
kodi-pvr-mythtv \
kodi-visualization* \
dbus-x11 \
vainfo \
x11-apps \
libcurl4-openssl-dev \
x11-xserver-utils \
coreutils \
nodejs \
npm \
kodi-inputstream-mpd

#####
# Install and configure 'kodi'
#####

##may need to add screensaver stop/start files to /usr/local/bin

ADD kodi_config_files.tar.gz /

# visualization.goom, visualization.projectm and visualization.spectrum are installed to the wrong location
#RUN mv /usr/lib/x86_64-linux-gnu/addons/* /usr/lib/kodi/addons
# TODO: fix: [ mv: target '/usr/lib/kodi/addons/' is not a directory ]

RUN ln /usr/bin/nodejs /usr/bin/node

EXPOSE 8080
EXPOSE 9090
EXPOSE 1900
EXPOSE 9777

RUN groupadd -g {{USER_GID}} {{USER}} && \
useradd {{USER}} -u {{USER_UID}} -g {{USER}} && \
echo "{{USER}}:{{PASSWORD}}" | chpasswd

#RUN useradd -G sound {{USER}}

RUN mkdir -p /home/{{USER}}/.config/pulse /home/{{USER}}/.pulse /home/{{USER}}/.kodi/temp
RUN chown {{USER}}:{{USER}} -R /home/{{USER}}

#COPY plugin.video.youtube-5.3.1.zip /plugin.video.youtube-5.3.1.zip
#RUN chown {{USER}.{{USER}} /plugin.video.youtube-5.3.1.zip

CMD ["/usr/local/bin/launchKodi.sh"]

#####
# Clean up
#####

RUN apt-get -y clean && \
rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

USER {{USER}}